version: '3.1'

services:
  production-build:
    image: mahulst/kafka-ui
    environment:
      - KAFKA_BROKER_LIST=kafka-1:19092
      - API_PORT=8081
    ports:
      - 8081:8081
    expose:
      - 8081
  service:
    environment:
      - KAFKA_BROKER_LIST=kafka-1:19092
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 19092
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
