[package]
name = "read-topic-api"
version = "0.1.0"
authors = ["mahulst <michel@voorkanter.com>"]
edition = "2018"

[dependencies]
log = "0.3.0"
env_logger = "0.6.1"
kafka = "0.7.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"